version: "3"
services:
  clickhouse:
    build: 
      context: ./clickhouse
    ports:
      - "8123:8123"
    volumes:
      - ./clickhouse/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./clickhouse/files:/files
    networks:
      - simplenet
  airflow:
    build: 
      context: airflow/
    ports:
      - "8080:8080"
    volumes:
      - ./airflow/dags:/usr/local/airflow/dags
    networks:
      - simplenet

networks:
  simplenet:
    external:
      name: simplenet
